### ISSUE TITLE
GMS2 Version?

### ISSUE THREAD

**Issue by GoldyFredy9** [bredi-amai/gmSMB#1]
The title is self explanitory, i had some trouble opening the source code into GM and im not entirely sure if i need a different version of GM to mess with the game's source. I downloaded the (latest?) windows version in GM's download page.

**Comment by bredi-amai** [comment]
Oh right, could be that I'm using a slightly older version of gamemaker
should have considered that, will update the project readme file with that

Tell me if it's working alright on the GMS2 version I put in there

**Comment by GoldyFredy9** [comment]
gotcha, i'll find the version listed in the readme and update progress here. Thanks!

**Comment by GoldyFredy9** [comment]
Redownloading the source and launching it in the version readme says works!
